"""Recognition-related schema package."""

from schemas.recognition import (
    PreprocessVersion,
    RecognitionAnswer,
    RecognitionBlock,
    RecognitionDocument,
    RecognitionGrading,
    RecognitionImage,
    RecognitionNode,
    RecognitionOverlayMark,
    RecognitionQuestionContract,
    RecognitionQuestionGroup,
    RecognitionRegion,
    build_answers,
    build_blocks_from_ocr_blocks,
    build_grading,
    build_question_groups,
    build_overlay_mark,
    build_question_contract,
    build_recognition_document,
    build_regions,
    identity_transform_matrix,
    normalize_bbox,
    normalize_confidence,
    should_drop_question_payload,
)

__all__ = [
    "PreprocessVersion",
    "RecognitionAnswer",
    "RecognitionBlock",
    "RecognitionDocument",
    "RecognitionGrading",
    "RecognitionImage",
    "RecognitionNode",
    "RecognitionOverlayMark",
    "RecognitionQuestionContract",
    "RecognitionQuestionGroup",
    "RecognitionRegion",
    "build_answers",
    "build_blocks_from_ocr_blocks",
    "build_grading",
    "build_question_groups",
    "build_overlay_mark",
    "build_question_contract",
    "build_recognition_document",
    "build_regions",
    "identity_transform_matrix",
    "normalize_bbox",
    "normalize_confidence",
    "should_drop_question_payload",
]
